### PR TITLE
Fix package unzipping when packed file name contains colon

### PR DESCRIPTION
**Pull request by Blackhex**
This happens e.g. when installing binaryen using `emsdk install binaryen-tag-1.38.31-64bit`.

### CODE REVIEW

**Comment by eukarpov** [comment]
what will happen with package when some files change their names after unpacking? Might it break some references?

**Review by eukarpov — COMMENTED** [review]
what will happen with package when some files change their names after unpacking? Might it break some references?

**Comment by Blackhex** [comment]
Yeah, it might. The poblem is that unzipping does the renaming so the unzipping should be "fixed". But colon is an invalid file name character on Windows so the unzipping can't be fixed that way. We can only ensure that the rest of the build process and the package (patched) codebase counts with the `:` -> `_` file name change what unzipping is doing. This PR is fixing it for unpacking/installation only.  There might be other changes needed elsewhere but assesing that will require using the installed package in different use-cases (at either compile-time or run-time). In other words, this PR is not solving the problem for good, it just makes it sligtly better and should not make it worse.

And sorry, just right now I've realized that my commit message is misleading in regards of the above.

**Comment by eukarpov** [comment]
> Yeah, it might. The poblem is that unzipping does the renaming so the unzipping should be "fixed". But colon is an invalid file name character on Windows so the unzipping can't be fixed that way. We can only ensure that the rest of the build process and the package (patched) codebase counts with the `:` -> `_` file name change what unzipping is doing. This PR is fixing it for unpacking/installation only.  There might be other changes needed elsewhere but assesing that will require using the installed package in different use-cases (at either compile-time or run-time). In other words, this PR is not solving the problem for good, it just makes it sligtly better and should not make it worse.
> 
> And sorry, just right now I've realized that my commit message is misleading in regards of the above.

Thank you for the clarification

**Review by eukarpov — APPROVED** [review]

**Pull request merged**
